# **NumPy Practice – Arrays, Indexing, Reshaping**

## Beginner Level

(Understand basic array creation and operations)



1.   Create a 1D NumPy array with values from 0 to 9.



In [1]:
import numpy as np

arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


2. Create a NumPy array filled with zeros, ones, and a custom constant (e.g., 7).


In [2]:
on = np.ones(10)
ze = np.zeros((3,2))
se = np.full((3,3), 7)

print(on)
print("*"*20)
print(ze)
print("*"*20)
print(se)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
********************
[[0. 0.]
 [0. 0.]
 [0. 0.]]
********************
[[7 7 7]
 [7 7 7]
 [7 7 7]]


3. Create a 2D array of shape (3, 3) with numbers from 1 to 9.



In [3]:
arr = np.arange(1, 10).reshape(3, 3)

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


4. Extract the first 3 elements from a 1D array.


In [4]:
arr1 = np.arange(10)
print(arr1)

first_three = arr1[:3]
print(first_three)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2]


5. Given an array [10, 20, 30, 40, 50], access the last two elements.



In [5]:
arr = [10, 20, 30, 40, 50]

last_two = arr[-2:]
print(last_two)

[40, 50]


6.   Slice the 2D array below to extract only the first two rows:

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

first_two_rows = arr[:2, :]
print(first_two_rows)

[[1 2 3]
 [4 5 6]]


7. Reshape a 1D array of 12 elements into a 3x4 2D array.



In [7]:
arr1 = np.arange(1, 13)

arr2 = arr1.reshape(3, 4)

print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Mid Level

(Apply indexing, slicing, reshaping in problem-solving)

1. Create an array of even numbers from 2 to 20.




In [8]:
arr = np.arange(2, 21, 2)
print(arr)


[ 2  4  6  8 10 12 14 16 18 20]


2. Generate a 4x4 identity matrix using NumPy.



In [9]:
iden = np.identity(4)
print(iden)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
iden = np.eye(4)
print(iden)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


3. Create a 3x3 matrix with random integers between 1 and 20. Find the max, min, and their indices.



In [11]:
arr = np.random.randint(1, 21, (3, 3))
print(arr)


maxx = arr.max()
minn = arr.min()

max_ind = np.unravel_index(arr.argmax(), arr.shape)
min_ind = np.unravel_index(arr.argmin(), arr.shape)

print(f"Maximum Value: {maxx} at index {max_ind}")
print(f"Minimum Value: {minn} at index {min_ind}")

# 🔹 Find ALL indices of max and min values
max_indices = np.argwhere(arr == maxx)
min_indices = np.argwhere(arr == minn)

print(f"All indices of Maximum Value {maxx}: {max_indices}")
print(f"All indices of Minimum Value {minn}: {min_indices}")

[[ 5 16 11]
 [19 20  1]
 [13 16 15]]
Maximum Value: 20 at index (np.int64(1), np.int64(1))
Minimum Value: 1 at index (np.int64(1), np.int64(2))
All indices of Maximum Value 20: [[1 1]]
All indices of Minimum Value 1: [[1 2]]


4. Replace all odd numbers in a NumPy array with -1.



In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Original Array:", arr)

arr[arr % 2 != 0] = -1
print("Modified Array:", arr)

Original Array: [1 2 3 4 5 6 7 8 9]
Modified Array: [-1  2 -1  4 -1  6 -1  8 -1]


5. Given a 1D array of 25 numbers, reshape it into a 5x5 matrix and extract the 2nd row.



In [13]:
arr = np.arange(25)

arr1 = arr.reshape(5, 5)

sec = arr1[1]

print(sec)

[5 6 7 8 9]


6. Stack two arrays vertically and horizontally:

a = np.array([1,2,3])
b = np.array([4,5,6])



In [14]:
a = np.array([1,2,3])
b = np.array([4,5,6])

v_stack = np.vstack((a, b))
h_stack = np.hstack((a, b))

print("Vertical Stack:\n", v_stack)
print("Horizontal Stack:\n", h_stack)

Vertical Stack:
 [[1 2 3]
 [4 5 6]]
Horizontal Stack:
 [1 2 3 4 5 6]


7. Flatten a 2D array into a 1D array.


In [15]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Flatten the array
flat1 = arr.flatten()   # returns a copy
flat2 = arr.ravel()     # returns a view (more memory efficient)

print("Original 2D Array:\n", arr)
print("Flattened with flatten():", flat1)
print("Flattened with ravel():", flat2)


Original 2D Array:
 [[1 2 3]
 [4 5 6]]
Flattened with flatten(): [1 2 3 4 5 6]
Flattened with ravel(): [1 2 3 4 5 6]


## Advanced Level

(More complex reshaping, fancy indexing, boolean masking)

1. Create a 5x5 matrix of random numbers and extract the diagonal elements.




In [16]:
import numpy as np

# Create a 5x5 random matrix (numbers 1–100 for clarity)
arr = np.random.randint(1, 101, size=(5, 5))

# Extract diagonal elements
diag = np.diag(arr)

print("5x5 Random Matrix:\n", arr)
print("Diagonal Elements:", diag)

5x5 Random Matrix:
 [[32 89 60  8 91]
 [80 50 48 91 28]
 [21 76  8 14 48]
 [50 34 56 20 22]
 [ 9 15 35  8 32]]
Diagonal Elements: [32 50  8 20 32]


2. Given a 4x4 matrix, replace the second column with all 0s.



In [17]:
import numpy as np

# Create a 4x4 matrix
arr = np.arange(1, 17).reshape(4, 4)

print("Original Matrix:\n", arr)

# Replace second column (index 1) with 0s
arr[:, 1] = 0

print("\nModified Matrix:\n", arr)

Original Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Modified Matrix:
 [[ 1  0  3  4]
 [ 5  0  7  8]
 [ 9  0 11 12]
 [13  0 15 16]]


3. Create a 10x10 matrix with values from 1 to 100, then extract all even numbers using boolean indexing.



In [18]:
import numpy as np

# Create 10x10 matrix with values 1 to 100
arr = np.arange(1, 101).reshape(10, 10)

print("Original 10x10 Matrix:\n", arr)

# Extract even numbers using boolean indexing
even_numbers = arr[arr % 2 == 0]

print("\nEven Numbers:\n", even_numbers)

Original 10x10 Matrix:
 [[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]

Even Numbers:
 [  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


4. Given:

arr = np.arange(1, 17).reshape(4,4)

Extract the sub-matrix:

[[6,7],
 [10,11]]



In [19]:
import numpy as np

arr = np.arange(1, 17).reshape(4, 4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [20]:
sub_matrix = arr[1:3, 1:3]
print(sub_matrix)

[[ 6  7]
 [10 11]]


5. Create a 6x6 array and reshape it into a 3D array of shape (2,3,6).



In [21]:
import numpy as np

# Step 1: Create a 6x6 array
arr = np.arange(1, 37).reshape(6, 6)
print("6x6 Array:\n", arr)

# Step 2: Reshape into 3D array (2, 3, 6)
arr_3d = arr.reshape(2, 3, 6)
print("\nReshaped 3D Array (2,3,6):\n", arr_3d)

6x6 Array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Reshaped 3D Array (2,3,6):
 [[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]
  [13 14 15 16 17 18]]

 [[19 20 21 22 23 24]
  [25 26 27 28 29 30]
  [31 32 33 34 35 36]]]


6. Use advanced indexing to pick elements at positions (0,0), (1,1), (2,2), (3,3) from a 2D array.



In [22]:
import numpy as np

# Create a 4x4 array
arr = np.arange(1, 17).reshape(4, 4)
print("Original Array:\n", arr)

# Advanced indexing: pick elements at (0,0), (1,1), (2,2), (3,3)
rows = [0, 1, 2, 3]
cols = [0, 1, 2, 3]

picked = arr[rows, cols]
print("\nPicked Elements:", picked)

Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Picked Elements: [ 1  6 11 16]


7. Create a random array of size 20 and sort it in ascending and descending order.



In [23]:
import numpy as np

# Create a random array of size 20 with integers between 1 and 100
arr = np.random.randint(1, 101, 20)
print("Original Array:\n", arr)

# Sort in ascending order
asc = np.sort(arr)
print("\nAscending Order:\n", asc)

# Sort in descending order
desc = np.sort(arr)[::-1]
print("\nDescending Order:\n", desc)

Original Array:
 [94 24 16 24 66 29 78 44 84 37 41 36 71 89 62 13 15 73 93  1]

Ascending Order:
 [ 1 13 15 16 24 24 29 36 37 41 44 62 66 71 73 78 84 89 93 94]

Descending Order:
 [94 93 89 84 78 73 71 66 62 44 41 37 36 29 24 24 16 15 13  1]
